bin/stagehand.dart
lib/src/cli_app.dart
pubspec.yaml

Upgrade to the latest version of `usage`.

update the version of usage that we depend on

---

.travis.yml
tool/drone.sh
tool/travis.sh

Switch to the new travis dart configuration.

switch to the new travis dart configuration

---

AUTHORS
lib/generators/ubersimplewebapp_data.dart
lib/src/cli_app.dart
pubspec.yaml

update authors; rev version

---

lib/src/cli_app.dart
lib/src/common.dart

remove project name validation

---

CHANGELOG.md
lib/src/cli_app.dart
pubspec.yaml

@sethladd - upgrade our usage dep to `1.0.0`

upgrade usage to 1.0.0

---

README.md
lib/stagehand.dart
site/index.html
tool/grind.dart

@sethladd, push the template descriptions into the documentation as part of a build step, to reduce busy-work when changing templates.

automate updating the docs

---

CHANGELOG.md
lib/src/cli_app.dart
lib/src/common.dart
pubspec.yaml

remove deprecated options; prep for a clean 0.2.0 release

---

pubspec.yaml
tool/grind.dart

upgrade grinder to 0.7.0

---

README.md
tool/grind.dart

Update how we auto-gen the template list. The html comments were leaking into the readme online.

update how we auto-gen the template list

---

site/index.html
site/styles.css

update the web site

---

tool/grind.dart

Cleanup pending migration to using pkg/test for each template

cleanup to grind test script

---

CHANGELOG.md
lib/src/cli_app.dart
pubspec.yaml
tool/grind.dart

- bump the stagehand version
- update the changelog
- shorten the grind script slightly
@kevmoo

bump the stagehand version; update changelog

---

test/validate_templates.dart
tool/grind.dart
tool/travis.sh

Runs all generators, even if one fails
Updated travis.sh

Make the generate validator use the test syntax

---

pubspec.yaml
test/validate_templates.dart
tool/grind.dart

- update to grinder 0.7.1 (capture some grinder fixes)

update to grinder 0.7.1

---

templates/web-polymer/README.md
templates/web-polymer/build.dart
templates/web-polymer/lib/main_app.dart
templates/web-polymer/lib/main_app.html
templates/web-polymer/pubspec.yaml
templates/web-polymer/web/index.dart
templates/web-polymer/web/index.html

**This version of polymer is not yet released, so please wait to merge**
Fixes https://github.com/dart-lang/polymer-dart/issues/552

update for polymer 1.0-rc1 (DO NOT MERGE)

---

CHANGELOG.md
pubspec.yaml

Rev. to 0.2.3; capture polymer template changes. @sethladd 
related to https://github.com/google/stagehand/issues/270

rev to 0.2.3; capture polymer template changes

---

templates/web-polymer/pubspec.yaml

As pointed out in https://github.com/google/stagehand/issues/269 I mixed these up

Fix up polymer version constraints

---

lib/generators/console_full.dart
lib/generators/console_simple.dart
lib/generators/package_simple.dart
lib/generators/server_appengine.dart
lib/generators/server_shelf.dart
lib/generators/web_polymer.dart
lib/generators/web_simple.dart
lib/src/cli_app.dart
pubspec.yaml
templates/console-simple/bin/main.dart
templates/server-appengine/bin/server.dart
templates/server-shelf/bin/server.dart
test/common_test.dart
test/validate_templates.dart
tool/grind.dart

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/google/stagehand/274)

A few tweaks

---

CHANGELOG.md
lib/generators/console_full_data.dart
lib/generators/console_simple_data.dart
lib/generators/package_simple_data.dart
lib/generators/server_appengine_data.dart
lib/generators/server_shelf_data.dart
lib/generators/web_polymer_data.dart
lib/generators/web_simple_data.dart
templates/server-appengine/lib/memcache.dart
tool/grind.dart

Follow up to https://github.com/google/stagehand/pull/276 -

re-gen sources

---

AUTHORS
CHANGELOG.md
lib/src/cli_app.dart
pubspec.yaml

@devoncarew I'd like to push the latest Angular template. LGTY?

Release 1.0.1

---

lib/generators/web_angular_data.dart
templates/web-angular/lib/app_component.css
templates/web-angular/lib/app_component.dart

As proposed in issue https://github.com/google/stagehand/issues/332

Add a component CSS file to the Angular template

---

CHANGELOG.md
pubspec.yaml
templates/web-angular/pubspec.yaml

Update web-angular to latest

---

templates/console-full/.analysis_options
templates/console-simple/.analysis_options
templates/package-simple/.analysis_options
templates/server-shelf/.analysis_options
templates/web-angular/.analysis_options
templates/web-polymer/.analysis_options
templates/web-simple/.analysis_options

Fixes https://github.com/google/stagehand/issues/341
@kevmoo  @filiph  @devoncarew, could one of you review? I am using this file in the Developer Workflow codelab. Thx!

Updating the analysis options file.

---

lib/generators/console_full_data.dart
lib/generators/console_simple_data.dart
lib/generators/package_simple_data.dart
lib/generators/server_shelf_data.dart
lib/generators/web_angular_data.dart
lib/generators/web_angular_quickstart_data.dart
lib/generators/web_simple_data.dart
tool/grind.dart

have the generated code use the current calendar year

---

lib/src/cli_app.dart
pubspec.yaml

- upgrade to usage 3.0.0
@kwalrath

upgrade to usage 3.0.0

---

site/index.html

Clarify that IDEs use Stagehand

---

.travis.yml
tool/travis.sh

This runs the web-angular template component tests on Travis.
Supersedes #398.
cc @filiph @kwalrath

Run web-angular component tests on Travis

---

.travis.yml

Fixes #422 by allowing dev builds to fail.
cc @kwalrath

chore(travis): allow dev builds to fail

---

analysis_options.yaml
templates/analysis_options.yaml
test/validate_templates.dart
tool/grind.dart

@kevmoo, @kwalrath, @chalin, update the analysis options excludes.

update the analysis options file

---

.travis.yml

See https://github.com/google/stagehand/issues/422#issuecomment-307879808.
cc @kwalrath

Remove allow_failures for dev channel

---

CHANGELOG.md
lib/src/cli_app.dart
pubspec.yaml

Bump SDK constraint to 2.0.0-dev.infinity

---

.gitignore
CHANGELOG.md
lib/generators/console_full_data.dart
lib/generators/package_simple_data.dart
lib/generators/server_shelf_data.dart
lib/generators/web_angular_data.dart
lib/generators/web_simple_data.dart
lib/generators/web_stagexl_data.dart
lib/src/cli_app.dart
pubspec.yaml
templates/console-full/.gitignore
templates/package-simple/.gitignore
templates/server-shelf/.gitignore
templates/web-angular/.gitignore
templates/web-simple/.gitignore
templates/web-stagexl/.gitignore
tool/version-check-and-update.sh

Fixes #459 
Related: https://github.com/dart-lang/site-www/issues/444

Add .dart_tool to .gitignore files

---

tool/travis.sh

Run dartfmt over template files

---

CHANGELOG.md
lib/generators/console_full_data.dart
lib/generators/package_simple_data.dart
lib/generators/server_shelf_data.dart
lib/generators/web_angular_data.dart
lib/generators/web_simple_data.dart
lib/generators/web_stagexl_data.dart
templates/console-full/CHANGELOG.md
templates/package-simple/CHANGELOG.md
templates/server-shelf/CHANGELOG.md
templates/web-angular/CHANGELOG.md
templates/web-simple/CHANGELOG.md
templates/web-stagexl/CHANGELOG.md

Template changelog cleanup

---

pubspec.yaml

Part of https://github.com/dart-lang/stagehand/issues/475

Update pubspec homepage to point to github.com/dart-lang/stagehand

---

CHANGELOG.md
lib/src/cli_app.dart
pubspec.yaml

OK to release stagehand 1.1.9?
/cc @kevmoo

Prepare to release 1.1.9

---

CHANGELOG.md

Edited CHANGELOG

---

tool/travis.sh

chore: re-enable coverage testing

---

CHANGELOG.md
lib/src/version.dart
pubspec.yaml

Prepare for 3.1.3 release.

---

CHANGELOG.md
build.yaml
lib/src/version.dart
pubspec.yaml

No urgency to publish an update

Update a number of dependencies

---

CHANGELOG.md
lib/src/version.dart
pubspec.yaml

Prep stagehand release

---

CHANGELOG.md
lib/src/version.dart
pubspec.yaml

- rev to 3.3.0-dev
@kevmoo @kwalrath

rev to 3.3.0-dev

---

.travis.yml
pubspec.yaml

Document VSCode Flutter Plugin requirements

---

README.md

With the Dart Code extension: see https://dartcode.org/releases/v2-23/

update README: VS Code supports Stagehand

---

CHANGELOG.md
lib/src/version.dart
pubspec.yaml

- prep for publishing 3.3.7
Capture the addition of the new template.

prep for publishing 3.3.7

---

CHANGELOG.md
pubspec.yaml

Stagehand 3.3.8 release

---

lib/src/version.dart
pubspec.yaml

- rev to 3.3.9 in prep for publishing (the changelog already contains info about the changes)
cc @jwren

rev to 3.3.9 in prep for publishing

---

.travis.yml
CHANGELOG.md
lib/src/generators/console_full.g.dart
lib/src/generators/console_simple.g.dart
lib/src/generators/package_simple.g.dart
lib/src/generators/server_shelf.g.dart
lib/src/generators/web_angular.g.dart
lib/src/generators/web_simple.g.dart
lib/src/generators/web_stagexl.g.dart
test/validate_templates.dart

Update generated code.

---

lib/src/version.dart
pubspec.yaml

Bump version for publishing

---

CHANGELOG.md
lib/src/cli_app.dart
lib/src/version.dart
pubspec.yaml

Prepare for https://github.com/dart-lang/http/issues/375

Pass a Uri to package:http APIs

---

lib/src/common.dart
test/common_test.dart

remove some unused methods

---

lib/src/generators/web_simple.g.dart
templates/web-simple/pubspec.yaml
templates/web-simple/web/main.dart

Just stumpled over it while testing some ideas.

Migrate web-simple template to null-safety

---

CHANGELOG.md
README.md
bin/stagehand.dart
lib/src/version.dart
pubspec.yaml

Fixes https://github.com/dart-lang/stagehand/issues/671

Discontinue package
