templates/console-full/.gitignore, templates/package-simple/.gitignore, templates/server-appengine/.gitignore, templates/server-shelf/.gitignore, templates/web-polymer/.gitignore, templates/web-simple/.gitignore
1. Include pattern for `pubspec.lock` in package-simple library package
only
1. Remove pattern for IntelliJ specific `.idea`
1. Remove pattern for MacOS specific `.DS_Store`
1. Update patterns for files and directories generated by *pub*
1. Add patterns for files generated by *dart2js*
1. Add pattern for directory created by *dartdoc*
Patterns for *pub*, *dart2js* and*dartdoc* are designed to work with Dart SDK 1.12, and are in sync with Dart .gitignore at https://github.com/github/gitignore.
Sources:
* https://www.dartlang.org/tools/private-files.html
* https://stackoverflow.com/questions/20314796/which-files-are-generated-when-executing-dart2js-and-why
* https://www.dartlang.org/tools/dart2js/
=> Update gitignore templates

templates/web-polymer/pubspec.yaml
If people use html imports containing dart scripts then the reflectable transformer needs to run on the bootstrap file, otherwise it can't reach the entire program.
=> Update reflectable entry point format

CHANGELOG.md, lib/src/cli_app.dart, pubspec.yaml
Rev to `0.2.6` to capture the latest updates to the angular and polymer templates.
https://github.com/google/stagehand/pull/299
https://github.com/google/stagehand/pull/298
=> rev to 0.2.6

site/index.html
`stagehand webapp` results in an error on my system. Changed to `stagehand web-simple`, which works.
=> Fix example on stagehand.pub

templates/server-shelf/bin/server.dart
Hi,
In order to make it easier to deploy simple test apps created with stagehand I suggest that the listener address is changed so that it works both on localhost and on any hosted platform, standalone VMs or PaaS alternatives. As a reference the [app engine example](https://github.com/dart-lang/appengine/blob/master/lib/src/server/server.dart#L30) already uses '0.0.0.0' instead of localhost.
=> Changed shelf listener address

.gitignore, lib/generators/console_simple.dart, lib/generators/web_simple.dart
rename some templates for consistency:
- one of the console app templates goes from `Console Application` to `Simple Console Application` (we had two templates with the same name)
- `Uber Simple Web Application` => `Simple Web Application` to match the above
@kwalrath @kevmoo
=> rename templates for consistency

CHANGELOG.md, lib/src/cli_app.dart, pubspec.yaml, templates/web-angular/lib/app_component.dart, templates/web-angular/lib/todo_list/todo_list_component.dart, templates/web-angular/pubspec.yaml
As per https://github.com/dart-lang/angular2/issues/363, this is deprecated.
Closes https://github.com/google/stagehand/issues/410.
=> Remove platform_* options from Angular pubspec

lib/generators/server_shelf.dart
Rename the `Shelf Web Server` app to `Web Server`. It's the only server app in the template list now, and we're not really trying to promote shelf (we still mention shelf in the template description).
=> rename 'Shelf Web Server' to 'Web Server'

.travis.yml, tool/build-check.sh, tool/env-set.sh, tool/travis.sh, tool/version-check-and-update.sh, tool/web-angular-test.sh
- Move web-angular test into its own job. Fixes #424.
- Add an app version consistency check. Fixes #432.
- Add a check that grind was run, as mentioned in #440.
<br>**Alternative:** instead we could just run grind `build` before deploying and avoid committing the built/generated files.
Note that `tool/version-check-and-update.sh` can be run to update the `lib/src/cli_app.dart` file using the app version in `pubspec.yaml`.
cc @kwalrath
=> Refactor and enhance Travis checks

site/index.html
The docs do not specify what it means that the "Dart SDK is on your path".
For someone who knows what this is, it is redundant and for others it may not mean much.
The patch intends to make it a more actionable step, if the command here fails because the Dart SDK is not found, *nix systems will at least complain with a standard `command not found: dart` and this can be debugged independently.
=> Update: installation documents to be explicit about checking version

lib/generators/console_full_data.dart, lib/generators/package_simple_data.dart, lib/generators/server_shelf_data.dart, lib/generators/web_angular_data.dart, lib/generators/web_simple_data.dart, lib/generators/web_stagexl_data.dart
Fixes #460 
Maybe we shouldn't be using the current year in the Copyright notice, but rather the year from the originating file? Anyhow, this is a quick fix to #460.
cc @kevmoo
=> chore: rerun grind to generate new copyright year

pubspec.yaml
- `stagehand` specified an older args, and was causing other packages to resolve to a pre-1.0 args
=> update to the latest args

tool/web-angular-test.sh
Build is currently broken, https://travis-ci.org/dart-lang/stagehand/jobs/383409929:
> Found 1 declared outputs which already exist on disk. This is likely because the`.dart_tool/build` folder was deleted, or you are submitting generated files to your source repository.
Delete these files?
1 - Delete
2 - Cancel build
3 - List conflicts
No output has been received in the last 10m0s
Hopefully this will fix it.
=> web-angular test --delete-conflicting-outputs

.gitignore, CHANGELOG.md, lib/src/generators/console_full.g.dart, lib/src/generators/package_simple.g.dart, lib/src/generators/server_shelf.g.dart, lib/src/generators/web_angular.g.dart, lib/src/generators/web_simple.g.dart, lib/src/generators/web_stagexl.g.dart, templates/console-full/.gitignore, templates/package-simple/.gitignore, templates/server-shelf/.gitignore, templates/web-angular/.gitignore, templates/web-simple/.gitignore, templates/web-stagexl/.gitignore
Dart 2 does not create a .pub directory
`build/` is not created by pub – move it to a new section
=> misc: cleanup .gitignore files across templates

CHANGELOG.md, lib/src/cli_app.dart, test/cli_test.dart
This adds the (existing) categories to the JSON output so that editors can filter them.
LMK if I should bump the version/add to changelog here (or include this in the other PR elsewhere..).
@kevmoo @devoncarew FYI!
=> Add categories to --machine output

tool/web-angular-test.sh
I don't think xvfb is required to run chrome tests anymore, but here goes...
=> Remove xvfb from web-angular-test.sh

.gitattributes
- don't collapse version.dart in github code reviews
@kwalrath 
See https://github.com/dart-lang/stagehand/pull/648/files for an example.
=> don't collapse version.dart in github code reviews

lib/stagehand.dart
TL;DR:
project name on `dart create <project-name>` must be normalized otherwise it fails while `pub get`.
Try to install dart project using `dart create` CLI helper.
```
$ dart create some-project
Creating /tmp/some-project using template console-simple...
.gitignore
CHANGELOG.md
README.md
analysis_options.yaml
bin/some-project.dart
pubspec.yaml
Running pub get...
Error on line 1, column 7 of pubspec.yaml: "name" field must be a valid Dart identifier.
╷
1 │ name: some-project
│       ^^^
╵
```
It should be normalized to `some_project` but it keeps as input and throws while `pub get`.
Throws 
```
Running pub get...
Error on line 1, column 7 of pubspec.yaml: "name" field must be a valid Dart identifier.
╷
1 │ name: some-project
│       ^^^
╵
```
Normalization is not done on neither …
=> project name must be normalized on generation

CHANGELOG.md, bin/stagehand.dart, lib/src/cli_app.dart, lib/src/common.dart, lib/src/generators/console_full.dart, lib/src/generators/console_full.g.dart, lib/src/generators/console_simple.dart, lib/src/generators/console_simple.g.dart, lib/src/generators/package_simple.dart, lib/src/generators/package_simple.g.dart, lib/src/generators/server_shelf.dart, lib/src/generators/server_shelf.g.dart, lib/src/generators/web_angular.dart, lib/src/generators/web_angular.g.dart, lib/src/generators/web_simple.dart, lib/src/generators/web_simple.g.dart, lib/src/generators/web_stagexl.dart, lib/src/generators/web_stagexl.g.dart, lib/src/version.dart, lib/stagehand.dart, pubspec.yaml, test/all.dart, test/cli_test.dart, test/common_test.dart, test/generators_test.dart, test/mock_test.dart, test/validate_templates.dart, tool/builder.dart, tool/src/code_generator.dart
Prepare for a beta release of 4.0.0 (that enables null safety by default). Per @devoncarew we don't want to publish this as a stable version before the next stable SDK, as that would cause some to get it prematurely.
=> Disable null safety and prepare for beta release

analysis_options.yaml, templates/analysis_options.yaml, templates/console-full/analysis_options.yaml, templates/console-simple/analysis_options.yaml, templates/package-simple/analysis_options.yaml, templates/server-shelf/analysis_options.yaml, templates/web-angular/analysis_options.yaml, templates/web-simple/analysis_options.yaml, templates/web-stagexl/analysis_options.yaml
Changed all http://dart-lang.github.io/linter/lints links to their https counterparts
=> Https links
